#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# displays Best School and then Hi on a new line for the 9th iteration
i=0
while ((i < 10))
do
	echo "Best School"
	if ((i == 8))
	then
		echo "Hi"
	fi
	((i+=1))
done
