#!/usr/bin/env bash
# a Bash script to displays "bad luck" @ 4th, "good luck" @ 8th & "Best School" @ otherwise loop 
i=1
while ((i <= 10))
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i+=1))
done
