#!/usr/bin/env bash
# A script to dislays "bad luck from" + country name for 4th, 9th & 17th loop respectively, otherwise number 1 to 20.
i=1
while ((i <= 20))
do
	echo $i
	case $i in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((i+=1))
done		
