#!/usr/bin/env bash
# A script that displays all active IPv4 on the machine it’s executed on
ip_addresses=$(hostname -I)
ip_addresses=(${ip_addresses//" "/ })
for ip in "${ip_addresses[@]}";
do
	printf "$ip\n"
done
